export const PROJECTS = [
  {
    id: 1,
    img: "/portfolio_images/terasus.png",
    title: "Terasus",
    description:
      "Save yourself the hassle of managing events with Terasus - fast, simple and reliable.",
    isTeamProject: false,
    link: "https://event-ticketer.vercel.app",
    technologies: [
      "ReactJS",
      "Tanstack Query",
      "Tailwind CSS",
      "Supabase",
      "Motion",
      "React Form Hook",
      "Context API",
    ],
  },
  {
    id: 2,
    img: "/portfolio_images/seekeroracle.png",
    title: "Seeker Oracle",
    description:
      "Truth Verified - Leverage decentralized AI agents to access verified, unbiased information in real-time.",
    isTeamProject: false,
    link: "https://www.seekeroracle.com/",
    technologies: [
      "ReactJS",
      "TailwindCSS",
      "HeadlessUI",
      "Motion",
      "Typescript",
    ],
  },
  {
    id: 3,
    img: "/portfolio_images/tetmart.png",
    title: "Tetmart Nigeria",
    description:
      "Tetmart is an E-Commerce platform built to provide visibility for students and small medium enterprise businesses within and outside campus.",
    link: "https://tetmart.ng",
    isTeamProject: false,
    technologies: [
      "ReactJS",
      "Tailwind CSS",
      "Zustand",
      "React Query",
      "React Form Hook",
      "Shadcn UI",
    ],
  },
  {
    id: 4,
    img: "/portfolio_images/tarioty.png",
    title: "Tarioty",
    description:
      "Tarioty is a dynamic creative studio that crafts engaging content across industries and borders, including 3D animation, gaming experiences, visual solutions, short films, series, architectural visualizations, and brand designs.",
    isTeamProject: false,
    link: "https://tarioty.vercel.app",
    technologies: ["ReactJS", "TypeScript", "Material UI", "Motion"],
  },
  {
    id: 5,
    img: "/portfolio_images/2077.png",
    title: "2077 Collective",
    description: `An information webpage made for the 2077 Collective campaign - "Let's make Ethereum cool again".`,
    isTeamProject: false,
    link: "https://2077collectiveframemaker.vercel.app",
    technologies: [
      "ReactJS",
      "TypeScript",
      "NextJS",
      "Motion",
      "Shadcn UI",
      "Tailwind CSS",
    ],
  },
  {
    id: 6,
    img: "/portfolio_images/bookam.png",
    title: "BOOKam",
    description: `A proposed terminal management system, and a ticket booking system for the Enugu State Government's terminal project.`,
    isTeamProject: true,
    link: "https://bookam-frontend.vercel.app",
    teamMembers: [
      {
        name: "Devtochukwu",
        pfp: "https://github.com/SimpleX-T.png",
        github: "https://github.com/SimpleX-T",
      },
      {
        name: "0xSolenoid",
        pfp: "https://github.com/solomonadzape95.png",
        github: "https://github.com/solomonadzape95",
      },
      {
        name: "Cyberdude",
        pfp: "https://github.com/engr-Godswillochi.png",
        github: "https://github.com/engr-Godswillochi",
      },
    ],
    technologies: [
      "TypeScript",
      "NextJS",
      "Motion",
      "Shadcn UI",
      "Tailwind CSS",
      "React Query",
      "React Form Hook",
      "Zod",
    ],
  },
];
